### ISSUE TITLE
Issue: "showCurrentDay"

### ISSUE THREAD

**Issue by P0larfoxx** [P0larfoxx/appointment-planner#1]
"showCurrentDay" is displayed 7 days in advance (instead of 12.11., the 20.11. is flagged as today)

**Comment by satinez** [comment]
did u fix it?

**Comment by P0larfoxx** [comment]
Good Morning,
Nope, didnt found the Problem yet.


satinez ***@***.***> schrieb am Sa., 13. Nov. 2021, 07:01:

**Comment by P0larfoxx** [comment]
issue solved by satinez
